name: Michael Lagman Photography
favicon: null
layout_spectrum: 0.9417344168759882
typography_spectrum: 0.3543416664469987
title: 'Wedding | Family | Senior photography in San Diego '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2b2b2b'
    - '#7d7d7d'
    - '#a5a5a5'
    - '#f2f2f2'
  brandStrength: 0.2379162
  lightness: 0.5340874143876135
  saturation: 0.1443501419853419
  rhythmicContrast: 0.8225703432690352
purpose: []
