name: Michael Lagman Photography
favicon: null
layout_spectrum: 0.9417344168759882
typography_spectrum: 0.3543416664469987
title: 'Wedding | Family | Senior photography in San Diego '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.11008942942135036
  lightness: 0.5340874143876135
  saturation: 0.1443501419853419
  rhythmicContrast: 0.8225703432690352
purpose: []
